# Generated by Django 4.2.13 on 2024-07-14 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='updated_on',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
