# Generated by Django 4.2.13 on 2024-07-21 00:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0002_patient_updated_on'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='address_line1',
            new_name='address_line_1',
        ),
        migrations.RenameField(
            model_name='patient',
            old_name='address_line2',
            new_name='address_line_2',
        ),
        migrations.RenameField(
            model_name='patient',
            old_name='address_line3',
            new_name='address_line_3',
        ),
    ]
